packages:
  - packages/*
  - playground/*

catalog:
  unbuild: ^3.6.1
  zod: "^3.0.0 || ^4.0.0"

catalogs:
  lint:
    "@antfu/eslint-config": ^6.6.1
    eslint: ^9.39.2
  playground:
    "@tailwindcss/vite": ^4.1.18
    tailwindcss: ^4.1.18
    vite: ^7.1.12
  solidjs:
    "@solidjs/testing-library": ^0.8.10
    solid-js: ">=1.9.0"
    vite-plugin-solid: ^2.11.10
  svelte:
    "@sveltejs/adapter-auto": ^7.0.0
    "@sveltejs/kit": ^2.49.2
    "@sveltejs/vite-plugin-svelte": ^6.2.1
    svelte: ">=5.0.0"
    svelte-check: ^4.3.4
    vitest-browser-svelte: ^2.0.1
  test:
    "@vitest/browser": ^4.0.15
    "@vitest/coverage-istanbul": ^4.0.15
    "@vitest/ui": ^4.0.15
    "@vitest/browser-playwright": ^4.0.15
    playwright: ^1.57.0
    vitest: ^4.0.15
  types:
    "@tsconfig/node22": ^22.0.5
    "@types/node": ^24.10.1
    typescript: ^5.9.3
  vue:
    "@vitejs/plugin-vue": ^6.0.3
    "@vue/tsconfig": ^0.8.1
    "@vue/devtools-api": "^8.0.5"
    vitest-browser-vue: ^2.0.1
    vue: ">=3.2.25"
    vue-tsc: ^3.1.8
