packages:
  - packages/*
  - playground/*

catalog:
  '@antfu/ni': ^25.0.0
  unbuild: ^3.5.0
  zod: '>=3.0.0'

catalogs:
  lint:
    '@antfu/eslint-config': ^4.13.2
    eslint: ^9.29.0
  playground:
    '@tailwindcss/vite': ^4.1.10
    tailwindcss: ^4.1.10
    vite: ^6.3.4
  solidjs:
    '@solidjs/testing-library': ^0.8.10
    solid-js: '>=1.9.0'
    vite-plugin-solid: ^2.11.6
  svelte:
    '@sveltejs/adapter-auto': ^6.0.1
    '@sveltejs/kit': ^2.21.5
    '@sveltejs/vite-plugin-svelte': ^5.1.0
    svelte: '>=5.0.0'
    svelte-check: ^4.2.1
    vitest-browser-svelte: ^0.1.0
  test:
    '@vitest/browser': ^3.2.3
    '@vitest/coverage-v8': ^3.2.3
    '@vitest/ui': ^3.2.3
    playwright: ^1.53.0
    vitest: ^3.2.3
  types:
    '@tsconfig/node22': ^22.0.2
    '@types/node': ^22.15.3
    typescript: ^5.8.3
  vue:
    '@vitejs/plugin-vue': ^5.2.4
    '@vue/tsconfig': ^0.7.0
    vite-plugin-vue-devtools: ^7.7.6
    vitest-browser-vue: ^0.2.0
    vue: '>=3.2.25'
    vue-tsc: ^2.2.10
