packages:
  - packages/*
  - playground/*

catalog:
  '@antfu/ni': ^27.0.0
  unbuild: ^3.6.1
  zod: '>=3.0.0'

catalogs:
  lint:
    '@antfu/eslint-config': ^6.0.0
    eslint: ^9.38.0
  playground:
    '@tailwindcss/vite': ^4.1.15
    tailwindcss: ^4.1.15
    vite: ^6.3.4
  solidjs:
    '@solidjs/testing-library': ^0.8.10
    solid-js: '>=1.9.0'
    vite-plugin-solid: ^2.11.9
  svelte:
    '@sveltejs/adapter-auto': ^7.0.0
    '@sveltejs/kit': ^2.47.1
    '@sveltejs/vite-plugin-svelte': ^6.2.1
    svelte: '>=5.0.0'
    svelte-check: ^4.3.3
    vitest-browser-svelte: ^1.1.0
  test:
    '@vitest/browser': ^4.0.1
    '@vitest/coverage-v8': ^4.0.1
    '@vitest/ui': ^4.0.1
    playwright: ^1.56.1
    vitest: ^4.0.1
  types:
    '@tsconfig/node22': ^22.0.2
    '@types/node': ^22.18.0
    typescript: ^5.9.3
  vue:
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/tsconfig': ^0.8.1
    vite-plugin-vue-devtools: ^8.0.3
    vitest-browser-vue: ^1.1.0
    vue: '>=3.2.25'
    vue-tsc: ^3.1.1
