packages:
  - packages/*
  - playground/*

catalog:
  '@antfu/ni': ^26.1.0
  unbuild: ^3.6.1
  zod: '>=3.0.0'

catalogs:
  lint:
    '@antfu/eslint-config': ^5.4.1
    eslint: ^9.37.0
  playground:
    '@tailwindcss/vite': ^4.1.14
    tailwindcss: ^4.1.14
    vite: ^6.3.4
  solidjs:
    '@solidjs/testing-library': ^0.8.10
    solid-js: '>=1.9.0'
    vite-plugin-solid: ^2.11.9
  svelte:
    '@sveltejs/adapter-auto': ^6.1.1
    '@sveltejs/kit': ^2.47.1
    '@sveltejs/vite-plugin-svelte': ^6.2.1
    svelte: '>=5.0.0'
    svelte-check: ^4.3.3
    vitest-browser-svelte: ^1.1.0
  test:
    '@vitest/browser': ^3.2.4
    '@vitest/coverage-v8': ^3.2.4
    '@vitest/ui': ^3.2.4
    playwright: ^1.56.1
    vitest: ^3.2.4
  types:
    '@tsconfig/node22': ^22.0.2
    '@types/node': ^22.18.0
    typescript: ^5.9.3
  vue:
    '@vitejs/plugin-vue': ^6.0.1
    '@vue/tsconfig': ^0.8.1
    vite-plugin-vue-devtools: ^8.0.2
    vitest-browser-vue: ^1.1.0
    vue: '>=3.2.25'
    vue-tsc: ^3.1.1
