name: CI

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - LICENSE

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Type check
        run: pnpm typecheck

  tests:
    strategy:
      matrix:
        zod-version: [v3, v4]
    runs-on: ubuntu-latest
    name: Tests - zod ${{ matrix.zod-version }}
    steps:
      - uses: actions/checkout@v5
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Install Playwright browsers
        run: pnpm exec playwright install

      - name: Install zod v3
        if: matrix.zod-version == 'v3'
        run: pnpm add zod@3 --filter @zorm-ts/core

      - name: Zod version
        run: pnpm list zod --filter @zorm-ts/core

      # Need to build the core package for reactivity tests
      - name: Build core
        run: pnpm build:core

      - name: Tests
        run: pnpm test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: ESLint
        run: pnpm lint

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build
        run: pnpm build
